<?php require('Views/templates/logheader.phtml');?>
<div id="wrapper">
    <div id="outer">
        <?php echo $view->linkSent;?>
        <div id="content">
            <p id="title">FORGOT PASSWORD</p>
            <form method="post">
                <label for="loginEmail">PLEASE ENTER YOUR EMAIL ADDRESS <?php echo $view->erremail;?></label>
                <input required type="email" id="loginEmail" name="typedEmail" placeholder="YOUR EMAIL ADDRESS...">
                <button id="loginButton" type="submit" name="forgotPassword">SEND RESET PASSWORD</button>
            </form>
            <p id="forgotPassword">Back to <a href="../login.php">LOGIN</a></p>
        </div>
        <img id="logo" src="../images/competa_logo_wit.svg" />
    </div>
</div>
