<?php require('Views/templates/logheader.phtml');?>
<div id="wrapper">
    <div id="outer">
        <div id="content">
            <p id="title">Password Reset</p>
            <form method="post">
                <label for="loginEmail">EMAIL ADDRESS <?php echo $view->erremail;?></label>
                <input required type="email" id="email" name="email" placeholder="Please enter your account email address...">
                <button id="loginButton" type="submit" name="loginButton">RESET</button>
            </form>
        </div>
        <img id="logo" src="../images/competa_logo_wit.svg" />
    </div>
</div>

