<?php require('Views/templates/logheader.phtml');?>
<?php
$user = $_SESSION['user'];
?>
<div class="border">
    <!-- top border  -->
</div>
<body>
<!--<link rel="stylesheet" href="/css/my-styles2.css">-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<div id="wrapper">
    <div id="outer">
        <div id="content">
<?php

        echo "
        
        <div class=\"col-xs-12 setPassword\">

            <p id=\"welcome\">Hi ".$view->user->getName()."!</p>
            <p id=\"pleaseSet\">Please Set Your New Password:</p>
            <br>
            <form action=\"../setpassword.php\" method=\"post\"> ".$view->err."
                <br>
                <br>
                <input required type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter Your New Password\">
                <br>
                <br>
                <input required type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm Your New Password\">
                <input type=\"hidden\" name=\"userId\" value='".$view->user->getUserid()."'>
        
                <input name=\"updatePassword\" id=\"passwordButton\"
                       type=\"submit\" value=\"Save password!\">
        
            </form>
        </div>
        
        ";

?>
        </div>
        <img id="logo" src="../images/competa_logo_wit.svg" />
    </div>
</div>

</body>
