<div class="border">
    <!-- top border  -->
</div>
<body>
<link rel="stylesheet" href="/css/my-styles2.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<?php
        echo "
        
        <div class=\"col-xs-12 setPassword\">

            <p id=\"welcome\">Hi ".$view->name."!</p>
            <p id=\"pleaseSet\">Please Set Your New Password:</p>
            <br>
            <form action=\"../updatepassword.php\" method=\"post\"> ".$view->err."
                <br>
                <br>
                <input required type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter Your New Password\">
                <br>
                <br>
                <input required type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm Your New Password\">
                <input type=\"hidden\" name=\"userId\" value='".$view->id."'>
        
                <input name=\"updatePassword\" id=\"passwordButton\" class=\"btn btn-block btn-large btn-success  green_btn\"
                       type=\"submit\" value=\"Save password!\">
        
            </form>
        </div>
        
        ";
?>


</body>
